### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by gmagno** [lionfish0/earclip#2]
Hey, it is great you have put this module together.

Just wanted to point out that there is no mention in your repo to the original license: https://github.com/mrbaozi/triangulation/blob/master/LICENSE. That is in violation of the MIT license.

Cheers,

**Comment by lionfish0** [comment]
Thanks for spotting that - added the MIT license.

**Comment by lionfish0** [comment]
Also - I'd like to really emphasise all credit should be mrbaozi's - I just needed this tool + it's easier to use if it's a module.

**Comment by lionfish0** [comment]
New license file: https://github.com/lionfish0/earclip/blob/master/LICENSE
